spring:
  profiles: generatesql
  flyway.enabled: false
  jpa.properties.javax.persistence.schema-generation.scripts:
    action: create
    create-target: V1__initial_script.sql
    create-source: metadata
spring.datasource.url=jdbc: jdbc:postgresql://localhost:7432/zamowbook
spring.datasource.username: root
spring.datasource.password: root123
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
