version: '3.1'

services:
  db:
    container_name: zamowbookdb
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: zamowbook
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
    ports:
      - 7432:5432